### ISSUE TITLE
Does not work with the latest Geyser version on 1.20. 

### ISSUE THREAD

**Issue by SonnenPingu** [rtm516/MCXboxBroadcast#28]
This extension is not loaded when you update the server to 1.20 So it is already loaded, but no connection to the bot is established 

Multiple reboots and reload but you don't get the link and the corresponding code

And standalone doesn't work for me, so I can't get that to work at all. 

I ask for a check and, if necessary, a fix.

**Comment by rtm516** [comment]
Please try wiping your config folder for the extension

**Comment by SonnenPingu** [comment]
I did. Ich habe sogar noch ein reload gemacht. 

Here's the log of what happened.

https://mclo.gs/41Uoe92

**Comment by axieum** [comment]
```
[10.06 16:08:03] [Server] [Thread-47/INFO]: [MCXboxBroadcast] Created Xbox session!
```

But it doesn't appear for anyone on Xbox, PC/mobile can join to the IP address however.

**Comment by tfo2020** [comment]
Hello,

I am also seeing this same issue.

PaperMC 1.20.1 (Build 43)
GeyserMC 210
Floodgate 59
MCXboxBroadcast 19 from Master

Running on Ubuntu Server 

In my server logs on startup of Minecraft I see the following error listed:

[16:15:28] [Server thread/ERROR]: [org.geysermc.geyser.event.GeyserEventBus] An exception occurred while executing event GeyserPostInitializeEvent for subscriber org.geysermc.geyser.event.GeyserEventSubscriber
java.lang.NoSuchMethodError: 'void org.yaml.snakeyaml.parser.ParserImpl.<init>(org.yaml.snakeyaml.reader.StreamReader)'
        at com.fasterxml.jackson.dataformat.yaml.YAMLParser.<init>(YAMLParser.java:191) ~[?:?]
        at com.fasterxml.jackson.dataformat.yaml.YAMLFactory._createParser(YAMLFactory.java:504) ~[?:?]
        at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:392) ~[?:?]
        at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:15) ~[?:?]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3542) ~[?:?]
        at com.rtm516.mcxboxbroadcast.bootstrap.geyser.MCXboxBroadcastExtension.onPostInitialize(MCXboxBroadcastExtension.java:71) ~[?:?]
        at org.lanternpowered.lmbda.Lmbda$1.accept(Unknown Source) ~[Geyser-Spigot.jar:?]
        at org.geysermc.event.subscribe.impl.SubscriberImpl.lambda$new$0(SubscriberImpl.java:55) ~[Geyser-Spigot.jar:?]
        at org.geysermc.event.subscribe.impl.SubscriberImpl.invoke(SubscriberImpl.java:75) ~[Geyser-Spigot.jar:?]
        at org.geysermc.event.bus.impl.BaseBusImpl.fireSilently(BaseBusImpl.java:201) ~[Geyser-Spigot.jar:?]
        at org.geysermc.event.bus.impl.OwnedEventBusImpl.fireSilently(OwnedEventBusImpl.java:41) ~[Geyser-Spigot.jar:?]
        at org.geysermc.event.bus.impl.BaseBusImpl.fire(BaseBusImpl.java:180) ~[Geyser-Spigot.jar:?]
        at org.geysermc.event.bus.impl.OwnedEventBusImpl.fire(OwnedEventBusImpl.java:41) ~[Geyser-Spigot.jar:?]
        at org.geysermc.geyser.GeyserImpl.startInstance(GeyserImpl.java:540) ~[Geyser-Spigot.jar:?]
        at org.geysermc.geyser.GeyserImpl.initialize(GeyserImpl.java:217) ~[Geyser-Spigot.jar:?]
        at org.geysermc.geyser.GeyserImpl.start(GeyserImpl.java:729) ~[Geyser-Spigot.jar:?]
        at org.geysermc.geyser.platform.spigot.GeyserSpigotPlugin.postStartup(GeyserSpigotPlugin.java:216) ~[Geyser-Spigot.jar:?]
        at org.geysermc.geyser.platform.spigot.GeyserSpigotPlugin$1.onServerLoaded(GeyserSpigotPlugin.java:185) ~[Geyser-Spigot.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-43]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-43]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-43]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:637) ~[paper-1.20.1.jar:git-Paper-43]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-43]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-43]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-43]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-43]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[16:15:28] [Server thread/INFO]: [Geyser-Spigot] Done (10.231s)! Run /geyser help for help!

If any additional information from my server would help I'm happy to provide it.

Thanks in advance!

**Comment by rtm516** [comment]
Fixed by https://github.com/rtm516/MCXboxBroadcast/commit/c7f5c087504af01b9fbb17996597c275ccd09a25
